### ISSUE TITLE
Redefine c! as separate for hashmap/list?

### ISSUE THREAD

**Issue by rivertam** [fangyuanziti/sugar-rs#4]
As discussed on Reddit, I think the `c!` macro is a little too ambiguous to quickly parse with the eye. Personally, I would prefer `list!` and `map!` macros rather than combining them so it's more obvious. I don't think the syntax needs to be so succinct that it only requires one letter, but `l!` (or maybe `v!` considering how hard on the eyes `l!` is) and `m!` might be better.

Just a suggestion for what I perceive to be an improvement to using sugar. It could also be that sugar offers both styles (to not break backwards compatibility and offer value to people with both opinions).

**Comment by rivertam** [comment]
Devil's Advocating myself:

-----

At least for naming: `list!` and `map!` don't imply in the names that they're comprehensions. `c!` makes it clear that we're not simply creating a list/map but rather that it's a special syntax. i.e. the name `v!` is not particularly clearly distinct from `vec!`.

-----

I feel like I've seen `map!` somewhere else?

**Comment by harryfei** [comment]
How about `list_c!` or `map_c!`? It is clearer but verboser.

Besides, I am considering (not decide) to add new macros as you said while keeping the old `c!` macro.

**Comment by rivertam** [comment]
It's a little too verbose for my tastes, but I definitely do prefer it over just `c!`. Maybe `lc!` and `mc!`? So far I like pretty much every idea in this thread :stuck_out_tongue:

**Comment by harryfei** [comment]
If more people can comment on this, it will be helpful for me.

**Comment by harryfei** [comment]
@rivertam Maybe I can add `lc!` and `mc!` as the alias for `c!`.

**Comment by rivertam** [comment]
@harryfei I think the issue with that is you can just use them opposite to each other. i.e. make a hashmap with `lc!`.

**Comment by harryfei** [comment]
After diging into the issues of [`cute`](https://github.com/mattgathu/cute/issues) project, I found there are 4 cases. 

* vec comprehension
* hashmap comprehension
* iterator comprehension
* generator comprehension

Our new name convention should match all of them.
@rivertam  What do you think?

**Comment by rivertam** [comment]
Yeah, I mean I guess it would be pretty much the same discussion, right? Just having four different macros. I think iterator comprehension is a little redundant with vecs (and maybe generators as well) as you could just run `.collect` on them, but it's all syntactic sugar so that seems fine I suppose.

**Comment by harryfei** [comment]
I am considering using those macros name.

* `v!`: vector comprehension (I prefer vector comprehension to list comprehension in Rust context).
* `m!`: hashmap comprehension
* `i!`: iterator comprehension
* `g!`: genertor comprehenison

**Comment by rivertam** [comment]
Seems good to me.
